version: '3.9'
services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./app:/var/www/html
    links:
      - redis

  redis:
    image: redis
    links:
      - mariadb
  
  mariadb:
    image: mariadb
    env_file:
      - mariadb/local.env
    restart: always
    volumes:
      - ./mariadb/db:/var/lib/mysqls
  
  composer:
    image: composer:latest
    command: install
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm
  
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    depends_on:
      - composer

  command:
    build: .
    command: 
      - /bin/sh 
      - -c 
      - |
        ls -la /var/www/html/public
        chown -R www-data /var/www/html/storage/logs
    volumes:
      - ./app:/var/www/html
    depends_on:
      - composer

  cronjobber:
    image: docker:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: cronjobber
    command: >
      sh -c "echo '* * * * * echo Crotab job loop working' > /etc/crontabs/root && crond -f"
    depends_on:
      - command


